//skilltest2024-backend\schema\schema.js
const schema = {
    admindb: {
        adminid: 'BIGINT PRIMARY KEY',
        password: 'LONGTEXT'
    },
    students: {
        student_id: 'BIGINT PRIMARY KEY',
        password: 'LONGTEXT',
        instituteId: 'BIGINT',
        batchNo: 'INT REFERENCES batchdb(batchNo)',
        batchdate: 'DATE',
        fullname: 'VARCHAR(100)',
        subjectsId: 'INT REFERENCES subjectsdb(subjectId)',
        courseId: 'INT',
        batch_year: 'VARCHAR(100)',
        loggedin: 'BOOLEAN',
        done: 'BOOLEAN',
        photo: 'LONGTEXT',
        center: 'INT REFERENCES examcenterdb(center)',
        reporting_time: 'TIME',
        start_time: 'TIME',
        end_time: 'TIME',
        day: 'INT',
        qset: 'INT',
        base64: 'LONGTEXT',
        sign_base64: 'LONGTEXT',
        IsShorthand: 'BOOLEAN',
        IsTypewriting: 'BOOLEAN',
        departmentId: 'INT REFERENCES departmentdb(departmentId)',
        disability: 'BOOLEAN',
        mothername: 'VARCHAR(100)'
    },
    subjectsdb: {
        subjectId: 'INT',
        examType: "ENUM('GCC', 'SKILL')",
        courseId: 'INT',
        subject_name: 'VARCHAR(100)',
        subject_name_short: 'VARCHAR(50)',
        daily_timer: 'INT',
        passage_timer: 'INT',
        demo_timer: 'INT',
        disability_passage_timer: 'INT',
        typing_timer: 'INT',
        disability_typing_timer: 'INT',
        'PRIMARY KEY': '(subjectId, examType)'
    },
    subjetsdb: {
        subjectId: 'LONGTEXT',
        courseId: 'LONGTEXT',
        subject_name: 'LONGTEXT',
        subject_name_short: 'LONGTEXT',
        daily_timer: 'LONGTEXT',
        passage_timer: 'LONGTEXT',
        disability_passage_timer: 'LONGTEXT',
        demo_timer: 'LONGTEXT',
        typing_timer: 'LONGTEXT',
        disability_typing_timer: 'LONGTEXT'
    },
    departmentdb: {
        departmentId: 'INT PRIMARY KEY',
        login_id: 'INT',
        examType: "ENUM('GCC', 'SKILL')",
        departmentName: 'VARCHAR(255)',
        departmentExam: 'LONGTEXT',
        departmentPassword: 'LONGTEXT',
        logo: 'LONGTEXT',
        departmentStatus: 'BOOLEAN'
    },
    studentlogs: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT',
        center: 'INT REFERENCES examcenterdb(center)',
        loginTime: 'TIMESTAMP NULL',
        login: 'BOOLEAN',
        trial_time: 'TIMESTAMP NULL',
        audio1_time: 'TIMESTAMP NULL',
        passage1_time: 'TIMESTAMP NULL',
        audio2_time: 'TIMESTAMP NULL',
        passage2_time: 'TIMESTAMP NULL',
        trial_passage_time: 'TIMESTAMP NULL',
        typing_passage_time: 'TIMESTAMP NULL',
        feedback_time: 'TIMESTAMP NULL',
        UNIQUE: '(student_id)'
    },
    loginlogs: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT REFERENCES studentlogs(student_id)',
        login_time: 'TIMESTAMP',
        ip_address: 'LONGTEXT REFERENCES pcregistration(ip_address)',
        disk_id: 'LONGTEXT',
        mac_address: 'LONGTEXT'
    },
    examcenterdb: {
        center: 'INT PRIMARY KEY',
        departmentId: 'INT',
        centerpass: 'LONGTEXT',
        center_name: 'VARCHAR(100)',
        center_address: 'VARCHAR(255)',
        pc_count: 'INT',
        max_pc: 'INT',
        attendanceroll: 'LONGTEXT DEFAULT NULL',
        absenteereport: 'LONGTEXT DEFAULT NULL',
        answersheet: 'LONGTEXT DEFAULT NULL',
        blankanswersheet: 'LONGTEXT DEFAULT NULL'
    },
    controllerdb: {
        center: 'INT REFERENCES examcenterdb(center)',
        batchNo: 'INT REFERENCES batchdb(batchNo)',
        departmentId: 'INT',
        controller_code: 'INT',
        controller_name: 'VARCHAR(100)',
        controller_contact: 'BIGINT',
        controller_email: 'VARCHAR(100)',
        controller_pass: 'LONGTEXT',
        district: 'VARCHAR(100)'
    },
    pcregistration: {
        id: 'INT AUTO_INCREMENT PRIMARY KEY',
        center: 'INT NOT NULL REFERENCES examcenterdb(center)',
        ip_address: 'LONGTEXT NOT NULL',
        disk_id: 'LONGTEXT NOT NULL',
        mac_address: 'LONGTEXT NOT NULL',
        processor: 'VARCHAR(255)',
        os: 'VARCHAR(255)',
        ram: 'VARCHAR(255)',
        total_storage: 'VARCHAR(255)',
        available_storage: 'VARCHAR(255)'
    },
    audiodb: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        subjectId: 'INT',
        qset: 'INT',
        departmentId: 'INT',
        examType: 'VARCHAR(20)',
        code_a: 'VARCHAR(25)',
        code_b: 'VARCHAR(25)',
        code_t: 'VARCHAR(25)',
        audio1: 'VARCHAR(255)',
        passage1: 'LONGTEXT',
        audio2: 'VARCHAR(255)',
        passage2: 'LONGTEXT',
        testaudio: 'VARCHAR(255)',
        textPassageA: 'LONGTEXT',
        textPassageB: 'LONGTEXT'
    },
    computertyping: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        subjectId: 'INT REFERENCES subjectsdb(subjectId)',
        qset: 'INT',
        trial_passage: 'LONGTEXT',
        passage_name: 'VARCHAR(10)',
        passage_text: 'LONGTEXT'
    },
    login_requests: {
        id: 'INT AUTO_INCREMENT PRIMARY KEY',
        ip_address: 'VARCHAR(255) NOT NULL',
        request_time: 'DATETIME NOT NULL',
        INDEX: '(ip_address, request_time)'
    },
    audiologs: {
        id: 'INT AUTO_INCREMENT PRIMARY KEY',
        student_id: 'BIGINT REFERENCES studentlogs(student_id)',
        trial: 'INT',
        passageA: 'INT',
        passageB: 'INT',
        UNIQUE: '(student_id)'
    },
    batchdb: {
        departmentId: 'INT REFERENCES departmentdb(departmentId)',
        batchNo: 'INT',
        batchdate: 'DATE',
        reporting_time: 'TIME',
        start_time: 'TIME',
        end_time: 'TIME',
        batchstatus: 'BOOLEAN'
    },
    feedbackdb: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'VARCHAR(255)',
        question1: 'VARCHAR(255)',
        question2: 'VARCHAR(255)',
        question3: 'VARCHAR(255)',
        question4: 'VARCHAR(255)',
        question5: 'VARCHAR(255)',
        question6: 'VARCHAR(255)',
        question7: 'VARCHAR(255)',
        question8: 'VARCHAR(255)',
        question9: 'VARCHAR(255)',
        question10: 'VARCHAR(255)'
    },
    textlogs: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT REFERENCES studentlogs(student_id)',
        mina: 'DECIMAL(10,0)',
        texta: 'TEXT',
        minb: 'DECIMAL(10,0)',
        textb: 'LONGTEXT',
        created_at: 'TIMESTAMP',
        UNIQUE: '(student_id)'
    },
    textlogs_history: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT',
        passage_identifier: 'VARCHAR(20) NOT NULL',
        text_content: 'TEXT',
        time_taken: 'FLOAT DEFAULT 0',
        created_at: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP',
        INDEX: '(student_id)'
    },
    finalPassageSubmit: {
        student_id: 'VARCHAR(255) PRIMARY KEY',
        passageA: 'LONGTEXT',
        passageB: 'LONGTEXT'
    },
    finalpassagesubmit: {
        student_id: 'BIGINT',
        passageA: 'LONGTEXT',
        passageB: 'LONGTEXT'
    },
    requestlogs: {
        id: 'INT PRIMARY KEY',
        ip_address: 'LONGTEXT',
        request_time: 'DATETIME'
    },
    expertreviewlog: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT',
        subjectId: 'INT',
        examType: "ENUM('GCC', 'SKILL')",
        qset: 'INT',
        departmentId: 'INT',
        expertId: 'INT',
        loggedin: 'DATETIME',
        status: 'BOOLEAN',
        subm_done: 'BOOLEAN DEFAULT 0',
        subm_time: 'DATETIME'
    },
    modreviewlog: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT',
        subjectId: 'INT',
        examType: "ENUM('GCC', 'SKILL')",
        qset: 'INT',
        departmentId: 'INT',
        expertId: 'INT',
        loggedin: 'DATETIME',
        status: 'BOOLEAN',
        subm_done: 'BOOLEAN DEFAULT 0',
        subm_time: 'DATETIME',
        hold: 'BOOLEAN DEFAULT 0',
        QPA: 'TEXT',
        QPB: 'TEXT'
    },
    modqsetdb: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        subjectId: 'INT',
        Q1PA: 'TEXT',
        Q1PB: 'TEXT',
        Q2PA: 'TEXT',
        Q2PB: 'TEXT',
        Q3PA: 'TEXT',
        Q3PB: 'TEXT',
        Q4PA: 'TEXT',
        Q4PB: 'TEXT',
        UNIQUE: '(subjectId)'
    },
    typingpassagelogs: {
        student_id: 'VARCHAR(50) PRIMARY KEY',
        trial_time: 'VARCHAR(255)',
        trial_passage: 'MEDIUMTEXT',
        passage_time: 'VARCHAR(255)',
        passage: 'MEDIUMTEXT',
        time: 'DATETIME'
    },
    typingpassage: {
        student_id: 'VARCHAR(50) PRIMARY KEY',
        trial_passage: 'MEDIUMTEXT',
        passage: 'MEDIUMTEXT',
        time: 'DATETIME'
    },
    expertdb: {
        expertId: 'INT PRIMARY KEY',
        password: 'VARCHAR(255)',
        expert_name: 'VARCHAR(255)',
        subject_50: 'BOOLEAN',
        subject_51: 'BOOLEAN',
        subject_52: 'BOOLEAN',
        subject_53: 'BOOLEAN',
        subject_54: 'BOOLEAN',
        subject_55: 'BOOLEAN',
        subject_56: 'BOOLEAN',
        subject_57: 'BOOLEAN',
        subject_60: 'BOOLEAN',
        subject_61: 'BOOLEAN',
        subject_62: 'BOOLEAN',
        subject_63: 'BOOLEAN',
        subject_70: 'BOOLEAN',
        subject_71: 'BOOLEAN',
        subject_72: 'BOOLEAN',
        subject_73: 'BOOLEAN',
        audio_rec: 'BOOLEAN',
        audio_mod: 'BOOLEAN',
        paper_check: 'BOOLEAN',
        paper_mod: 'BOOLEAN',
        super_mod: 'BOOLEAN'
    },
    qsetdb: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        subjectId: 'INT REFERENCES subjectsdb(subjectId)',
        departmentId: 'INT REFERENCES departmentdb(departmentId)',
        Q1PA: 'TEXT',
        Q1PB: 'TEXT',
        Q2PA: 'TEXT',
        Q2PB: 'TEXT',
        Q3PA: 'TEXT',
        Q3PB: 'TEXT',
        Q4PA: 'TEXT',
        Q4PB: 'TEXT',
        Q5PA: 'TEXT',
        Q5PB: 'TEXT',
        Q6PA: 'TEXT',
        Q6PB: 'TEXT',
        Q7PA: 'TEXT',
        Q7PB: 'TEXT',
        Q8PA: 'TEXT',
        Q8PB: 'TEXT'
    },
    answersheet: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT',
        image1: 'LONGTEXT',
        image2: 'LONGTEXT',
        image3: 'LONGTEXT',
        image4: 'LONGTEXT',
        upload_date: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
    },
    attendance_reports: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        center: 'VARCHAR(255)',
        batchNo: 'VARCHAR(50)',
        departmentId: 'INT',
        report_date: 'DATETIME',
        present_count: 'INT',
        absent_count: 'INT',
        attendance_pdf: 'VARCHAR(255)',
        upload_time: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP'
    },
    resetrequests: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT',
        reason: 'LONGTEXT',
        reseted_by: 'TEXT',
        reset_type: 'TEXT',
        approved: 'TEXT',
        center: 'INT REFERENCES examcenterdb(center)',
        time: 'DATETIME'
    },
    features: {
        feature: 'TEXT',
        status: 'BOOLEAN',
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT'
    },
    exam_stages: {
        StudentId: 'BIGINT REFERENCES students(student_id)',
        StudentInfo: 'BOOLEAN DEFAULT 0',
        Instructions: 'BOOLEAN DEFAULT 0',
        InputChecker: 'BOOLEAN DEFAULT 0',
        HeadphoneTest: 'BOOLEAN DEFAULT 0',
        ControllerPassword: 'BOOLEAN DEFAULT 0',
        TrialPassage: 'BOOLEAN DEFAULT 0',
        AudioPassageA: 'BOOLEAN DEFAULT 0',
        TypingPassageA: 'BOOLEAN DEFAULT 0',
        AudioPassageB: 'BOOLEAN DEFAULT 0',
        TypingPassageB: 'BOOLEAN DEFAULT 0',
        TrialTypewriting: 'BOOLEAN DEFAULT 0',
        Typewriting: 'BOOLEAN DEFAULT 0',
        ShorthandSummary: 'BOOLEAN DEFAULT 0',
        ShorthandSummaryB: 'BOOLEAN DEFAULT 0',
        TypingSummary: 'BOOLEAN DEFAULT 0',
        FeedbackForm: 'BOOLEAN DEFAULT 0',
        ThankYou: 'BOOLEAN DEFAULT 0',
        INDEX: '(StudentId)'
    },
    trackrecord: {
        student_id: 'VARCHAR(50) PRIMARY KEY',
        PA_datetime: 'DATETIME',
        PB_datetime: 'DATETIME',
        PA_filename: 'VARCHAR(255)',
        PB_filename: 'VARCHAR(255)'
    },
    failed_zips: {
        student_id: 'VARCHAR(50) PRIMARY KEY',
        filename: 'VARCHAR(255)',
        failure_time: 'DATETIME',
        passage_type: 'VARCHAR(50)',
        last_error: 'MEDIUMTEXT',
        status: "VARCHAR(50) DEFAULT 'pending'",
        updated_at: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
    },
    resettablelogs: {
        id: 'BIGINT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'BIGINT NOT NULL',
        timeStamp: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
        studentLogin: 'BOOLEAN DEFAULT 0',
        studentDone: 'BOOLEAN DEFAULT 0',
        audioShorthandA: 'BOOLEAN',
        textShorthandA: 'BOOLEAN',
        textTyping: 'BOOLEAN DEFAULT 0',
        reason: 'VARCHAR(255)',
        trialAudioShortHand: 'BOOLEAN DEFAULT 0',
        trialTextShortHand: 'BOOLEAN DEFAULT 0',
        trialText: 'BOOLEAN DEFAULT 0',
        audioShorthandB: 'BOOLEAN',
        textShorthandB: 'BOOLEAN'
    },
    system_settings: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        setting_key: 'VARCHAR(255)',
        setting_value: 'TEXT',
        created_at: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP',
        updated_at: 'TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
        UNIQUE: '(setting_key)'
    },
    blank_passage_submissions: {
        id: 'INT PRIMARY KEY AUTO_INCREMENT',
        student_id: 'VARCHAR(50) NOT NULL',
        center: 'VARCHAR(50) NOT NULL',
        batchNo: 'VARCHAR(50)',
        passage_type: "VARCHAR(50) DEFAULT 'unknown'",
        submitted_at: 'DATETIME DEFAULT CURRENT_TIMESTAMP',
        center_comment: 'TEXT',
        commented_by: 'VARCHAR(100)',
        commented_at: 'DATETIME',
        admin_viewed: 'BOOLEAN DEFAULT 0',
        admin_viewed_at: 'DATETIME',
        INDEX: '(student_id), (center), (batchNo)'
    }
};

module.exports = schema;